# See https://symfony.com/doc/current/email/dev_environment.html
swiftmailer:
    default_mailer: no_reply
    mailers:
        no_reply: 
            url: '%env(MAILER_URL)%'
    # transport: gmailer
    # username: celes.thym@gmail.com
    # password: latete33
    # send all emails to a specific address
    #delivery_addresses: ['me@example.com']
